# Generated by Django 5.0.6 on 2024-05-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('course', 'Course'), ('conference', 'Conference'), ('workshop', 'Workshop')], max_length=10),
        ),
    ]
