# Generated by Django 5.0.6 on 2024-05-17 02:33

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='passcode',
            field=models.CharField(default=App.models.generate_passcode, max_length=6, unique=True),
        ),
    ]
