# Generated by Django 5.0.6 on 2024-05-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_registration_passcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='passcode',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
