# Generated by Django 5.0.6 on 2024-05-20 06:17

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_registration_rating_registration_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='review',
        ),
        migrations.AlterField(
            model_name='registration',
            name='passcode',
            field=models.CharField(default=App.models.generate_passcode, max_length=6, unique=True),
        ),
    ]
