# Generated by Django 5.0.6 on 2024-05-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_registration_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
