# Generated by Django 5.0.6 on 2024-05-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_event_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reviews_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
