# Generated by Django 5.0.6 on 2024-05-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_event_reviews_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
